# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - InventoryManagementSystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deploy & docker
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7F8EB15A0F3F4426AA5DE2C0921189C7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE9A67F36DF54CB196DF4FF723FE63D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E01D85030F5748A99F37433AD2BA8580 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name:  InventoryManagementSystem
          slot-name: Production
          package:   .

  offline:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        
      - name: Download published app
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
        
      - name: Build Docker image
        run: |
          docker build -t ims-offline:${{ github.sha }} ./myapp
        
      - name: Save image as tarball
        run: |
          docker save ims-offline:${{ github.sha }} \
          | gzip > ims-offline_${{ github.sha }}.tar.gz
        
      - name: Upload offline image
        uses: actions/upload-artifact@v4
        with:
          name: offline-docker-image
          path: ims-offline_${{ github.sha }}.tar.gz

      - name: Pull & save SQL Server image
        run: |
          docker pull mcr.microsoft.com/mssql/server:2019-latest
          docker save mcr.microsoft.com/mssql/server:2019-latest \
          | gzip > sqlserver_2019.tar.gz
  
      - name: Upload SQL Server image
        uses: actions/upload-artifact@v4
        with:
          name: offline-sqlserver-image
          path: sqlserver_2019.tar.gz
  